[features]
resolution = true
skip-lint = false

[programs.localnet]
service_referral_protocol = "4AuoBkj4vkH2K1jwUuECtVBqF6Q74efjGbaw7btuNjRV"
revenue_adapter = "EmGJDPvwSx6kU4KijWGh8uqRNj3BJXNjcWQyCmfKv7WL"

[programs.devnet]
service_referral_protocol = "4AuoBkj4vkH2K1jwUuECtVBqF6Q74efjGbaw7btuNjRV"
revenue_adapter = "EmGJDPvwSx6kU4KijWGh8uqRNj3BJXNjcWQyCmfKv7WL"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "node tests/reference-model.mjs"
